# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0e5aa4cb1701e64b8e5fe6e2cf65ff4d4da67917c2e59f6d66dacfff67d0874886a618a67c1262bcadb92ba46ff1314c3aa1f724ca4eeb725039c76c172448d2

test:
  secret_key_base: c26d4d911f9a311d2fd1a57762fd6a7d17c624bc9147c9985fa1f84823d90a8e38bcab9f1976fe7e7ff9fe4dacea05893a19aeec11a059ca891ce8dad16e7098

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
